trigger:
- master
- maint/*

jobs:
- job: windows_amd64
  displayName: 'Windows (amd64)'
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - template: azure-pipelines-build.yml

- job: macos
  displayName: 'macOS'
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - template: azure-pipelines-build.yml
